version: "3"  # Docker Compose 文件版本

services:
  nginx:
    image: nginx:latest  # 使用最新的 nginx 镜像
    container_name: blog-nginx  # 设置容器名称
    ports:
      - 9020:80  # 将容器的80端口映射到宿主机的80端口
    volumes:
      - D:/Users/tangk/Desktop/code/blog/docker-volumes/nginx/html:/usr/share/nginx/html  # 映射静态文件目录
      - D:/Users/tangk/Desktop/code/blog/docker-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf  # 映射 nginx 配置文件
      - D:/Users/tangk/Desktop/code/blog/docker-volumes/nginx/blog_images:/usr/share/nginx/blog_images  # 映射 8964 端口 的图片
      # - /root/code/blog/docker-volumes/nginx/html:/usr/share/nginx/html
      # - /root/code/blog/docker-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blog_network  # 连接到自定义网络

  mysql:
    image: mysql:8.0.35  # 使用指定版本的 MySQL 镜像
    container_name: blog-mysql  # 设置容器名称
    ports:
      - 9021:3306  # 将容器的3306端口映射到宿主机的9011端口
    environment:
      - MYSQL_ROOT_PASSWORD=1209  # 设置 MySQL root 用户的密码
    volumes:
      - D:/Users/tangk/Desktop/code/blog/docker-volumes/mysql/data:/var/lib/mysql  # 映射 MySQL 数据目录
      - D:/Users/tangk/Desktop/code/blog/docker-volumes/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化脚本
      # - /root/code/blog/docker-volumes/mysql/data:/var/lib/mysql
      # - /root/code/blog/docker-volumes/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    networks:
      - blog_network  # 连接到自定义网络
  fastapi:
    image: blog:latest  # 使用构建的最新 FastAPI 镜像
    container_name: blog-fastapi  # 设置容器名称
    build: .  # 从当前目录构建镜像
    ports:
      - 9023:8080  # 将容器的8080端口映射到宿主机的9013端口
    depends_on:
      - mysql  # 确保 mysql 服务在 fastapi 启动之前启动
    networks:
      - blog_network  # 连接到自定义网络

networks:
  blog_network:
    driver: bridge  # 使用 bridge 网络驱动
